#Config File example
save_dir: workspace/nanodet_m_hand_ego_GRAY
model:
  arch:
    name: OneStageDetector
    backbone:
      name: ShuffleNetV2
      model_size: 1.0x
      out_stages: [2,3,4]
      activation: LeakyReLU
    fpn:
      name: PAN
      in_channels: [116, 232, 464]
      out_channels: 96
      start_level: 0
      num_outs: 3
    head:
      name: NanoDetHead
      num_classes: 2 #Please fill in the number of categories (not include background category)
      input_channel: 96
      feat_channels: 96
      stacked_convs: 2
      share_cls_reg: True
      octave_base_scale: 5
      scales_per_octave: 1
      strides: [8, 16, 32]
      reg_max: 7
      norm_cfg:
        type: BN
      loss:
        loss_qfl:
          name: QualityFocalLoss
          use_sigmoid: True
          beta: 2.0
          loss_weight: 1.0
        loss_dfl:
          name: DistributionFocalLoss
          loss_weight: 0.25
        loss_bbox:
          name: GIoULoss
          loss_weight: 2.0

class_names: &class_names ['lefthand', 'righthand']  #Please fill in the category names (not include background category)
data:
  train:
    name: [XMLDataset]
    class_names: *class_names
    img_path: [data/ego/JPEGImages]  #Please fill in train image path
    ann_path: [data/ego/Annotations]  #Please fill in train xml path
    to_gray: True
    input_size: [320,320] #[w,h]
    keep_ratio: True
    pipeline:
      perspective: 0.0
      scale: [0.6, 1.4]
      stretch: [[1, 1], [1, 1]]
      rotation: 0
      shear: 0
      translate: 0.2
      flip: 0
      brightness: 0.2
      contrast: [0.8, 1.2]
      saturation: [0.8, 1.2]
      normalize: [[0, 0, 0], [255, 255, 255]]
  val:
    name: [DOHDataset]
    class_names: *class_names
    img_path: [data/100DOH/raw] #Please fill in val image path
    ann_path: [data/100DOH/file/test.json] #Please fill in val xml path
    to_gray: True
    input_size: [320,320] #[w,h]
    keep_ratio: True
    pipeline:
      normalize: [[0, 0, 0], [255, 255, 255]]
device:
  gpu_ids: -1
  workers_per_gpu: 4
  batchsize_per_gpu: 96
schedule:
#  resume:
  load_model: /mnt/lustre/duanyongli/WorkSpace/nanodet/workspace/nanodet_m_hand_100DOH_GRAY/model_best/model_best.ckpt
  optimizer:
    name: SGD
    lr: 0.56
    momentum: 0.9
    weight_decay: 0.0001
  warmup:
    name: linear
    steps: 300
    ratio: 0.1
  total_epochs: 200
  lr_schedule:
    name: MultiStepLR
    milestones: [70,120,160,180]
    gamma: 0.1
  val_intervals: 10
evaluator:
  name: CocoDetectionEvaluator
  save_key: mAP

log:
  interval: 10
